export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const GETUSERDETAILS = 'GETUSERDETAILS';
export const GETACCEPT_STATUS = 'GETACCEPT_STATUS';
export const GETREQUEST_STATUS = 'GETREQUEST_STATUS';